language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
    - libgtk-3-bin
    - libgtk-3-dev
    - libpango1.0-0
before_install:
 - sudo apt-get install libasound2-dev alsa-utils alsa-oss
 - sudo modprobe snd-dummy