[package]
name = "rusty_microphone"
version = "0.1.0"
authors = ["Justin Worthe <justin.worthe@gmail.com>"]

[dependencies]
bencher = "0.1.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
portaudio = "0.7.0"
gtk = "0.3.0"
cairo-rs = "0.3.0"

[[bench]]
name = "transforms"
harness = false