[package]
name = "rusty_microphone"
version = "0.1.0"
authors = ["Justin Worthe <justin.worthe@gmail.com>"]

[dependencies]
portaudio = "0.7.0"
dft = "0.4.3"
cairo-rs = "0.1.1"

[dependencies.gtk]
version = "0.1.1"
features = ["v3_10"]