[package]
name = "rusty_microphone"
version = "0.1.0"
authors = ["Justin Worthe <justin.worthe@gmail.com>"]

[dependencies]
portaudio = "0.7.0"
gtk = "0.1.1"
cairo-rs = "0.1.1"
bencher = "0.1.2"

[[bench]]
name = "transforms"
harness = false